### ISSUE TITLE
Thoughts on interface cleanup

### ISSUE THREAD

**Issue by kirbysayshi** [jclem/gifify#14]
#11's README mentions made me wonder: are you, @jclem open, at some point, to a revamp of the flags? Some changes I've been thinking of making:

- make `-n` the default behavior, or assume the command should be `gifify file.mp4 | cloudup`
- remove the `-o`, assume user will redirect (maybe)?
- merge `-r` and `-s` since they are dependent on each other, perhaps something like `gifify -r 1.5@30` (1.5x speed, output at 30fps)

Maybe others?

**Comment by jakebellacera** [comment]
:+1:

**Comment by jclem** [comment]
I've implemented this except for the piping. In my experience, people typically don't really care about the resulting filename, so I'd rather avoid requiring redirecting output.
