### ISSUE TITLE
Loop option

### ISSUE THREAD

**Issue by joeyhoer** [jclem/gifify#20]
It would be nice to have an option that controls the looping of the output file.

**Comment by joeyhoer** [comment]
I've added this to [my fork](https://github.com/joeyhoer/gifify), unfortunately I didn't keep the commits separate, so it will be difficult to merge. The example implementation works well.

**Comment by jclem** [comment]
Done in https://github.com/jclem/gifify/commit/79930e64356652064852ee1db2edd3e0406b4091
