### ISSUE TITLE
options to process a bunch of files

### ISSUE THREAD

**Issue by sinsunsan** [jclem/gifify#27]
Pers aps it's out of scope, but would be useful to be able to process a bunch of files, in the current dir, or in a given directory. Indeed the workflow is generally (at least in my cases) to convert several files from video to git. O course, I can make my own shell stuff, but don't now how to do that, and would be integrated with gifify which is better :)

A problem that I would have is when I want to handle custom output names, for different files, there is no options to customize file name, depending of original file name, like appending always -S or -M ... to original file name ?

**Comment by jclem** [comment]
I consider this out of gifify's scope. One way to do this would be:

```sh
for file in ./*.mov; do
  gifify -o $file-S $file
done
```
