### ISSUE TITLE
Do not upload to CloudApp by default

### ISSUE THREAD

**Issue by lacymorrow** [jclem/gifify#28]
The default integration with cloudapp makes this tool much more specialized. I understand that many people will want to upload their created GIFs to share, but making that the default behavior, and especially only providing that single interface seems counterintuitive.

You've made a great CLI tool for `creating GIFs from videos`, and you would attract a much larger following and userbase if it did not come off as a specialty tool for `creating GIFs from videos AND uploading them to CloudApp`. It also adds one more dependency to get up and running with the default settings.

Wonderful tool and thank you so much for creating it, but I have no need to share GIFs, nor have I ever heard of CloudApp. I'm sure I am not alone in this stance :) 

The integration is an awesome addition, I just wouldn't have it be the default behavior.

**Comment by dannguyen** [comment]
Agree...the CloudApp functionality has never worked for me and not only is that side effect unexpected, the program simply doesn't even create an output GIF if the CloudApp part fails.

**Comment by jclem** [comment]
I plan on removing it entirely when I have time for an update. I don't use CloudApp at all currently, myself.

**Comment by joeyhoer** [comment]
The dependency on CloudApp is too prescriptive IMO, and should probably be removed.

**Comment by Alhadis** [comment]
Agreed. I don't even have CloudApp installed on this thing, haha.

**Comment by jclem** [comment]
Closed by https://github.com/jclem/gifify/commit/e86a15123d45a796aec7d1d4c8d15d8e121bd55c
