### ISSUE TITLE
Perform operations in memory

### ISSUE THREAD

**Issue by joeyhoer** [jclem/gifify#31]
Writing and reading to/from the disk is slow. I would suggest performing operations over a pipe to improve performance:

```
ffmpeg -loglevel panic -i "$filename" $filter -r $fps -f image2pipe -vcodec ppm - | \
  convert +dither -layers Optimize -loop $loop -delay $delay - "${output}.gif"
```

Conditionally, we could allow data to be written to the disk to preserve memory.

**Comment by jclem** [comment]
I can't really see an appreciable difference here, at least on the short length of videos that people typically convert with gifify.
