### ISSUE TITLE
Converting creates gigantic tmp files

### ISSUE THREAD

**Issue by chasegiunta** [jclem/gifify#35]
Converting a 7MB mp4 video creates a 4.8GB temp file, and will hang until operation is cancelled.

**Comment by nloveladyallen** [comment]
I had a 350K .mov file, the script made a _65M_ temp file. 4.8M is excusable, but 65M is not.

**Comment by jclem** [comment]
It's true, it's inexcusable, and I'm ashamed.

Just kidding! This is the ffmpeg part of the conversion. If you're using this on a system where creating large temp files is not excusable I would **strongly advise against using gifify**.

Seriously, all this does is create a file with ffmpeg and then convert it into a gif using ImageMagick. There are **way** better solutions, but this one works best for me and some other people.

That said, if you know of a way to do this reliably using pipes and without a temp file, I'd happily update it.

**Comment by chasegiunta** [comment]
@jclem Closing, as this is the intended behavior.

**Comment by jclem** [comment]
@ChaseGiunta I'd definitely like to find a more efficient way to do this, I just haven't had time to look into it yet. I just took some offense to being told that there is no excuse for it.

**Comment by chasegiunta** [comment]
Totally mistyped the _after_ value btw... Supposed to be 4.8 _GB_

**Comment by jclem** [comment]
That I've definitely never seen in the entire time I've been using this. Is this reproducible with other files? I'm using a fairly standard ffmpeg command.
