### ISSUE TITLE
Add Scaling

### ISSUE THREAD

**Issue by ProLoser** [jclem/gifify#8]
I would like to be able to scale down the resolution/size/quality of the video so it doesn't stay so large.

**Comment by sinsunsan** [comment]
Thanks for the option, but how to use it with a brew install ? 
Indeed, there is no release with this fix. 
The only thing that I imagine is to clone the repo but not very convenient, any idea ? @kirbysayshi

**Comment by kirbysayshi** [comment]
@jclem could you make a release for homebrew?

@sinsunsan I've been just cloning the repo and putting it into my path,  or just manually call it.

**Comment by jclem** [comment]
@kirbysayshi @sinsunsan PR submitted https://github.com/Homebrew/homebrew/pull/40111
